name: Publish
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ README.md ]
  release:
    types: [ published ]

jobs:
  publish-plugin:
    name: Publish plugin
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Set up JDK
        uses: actions/setup-java@v5.7.0
        with:
          distribution: temurin
          java-version: 25
          cache: gradle

      - name: Publish to Modrinth
        env:
          RELEASE: true
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          VERSION_NAME: ${{ github.event.release.name }}
          VERSION: ${{ github.event.release.tag_name }}
          CHANGELOG: ${{ github.event.release.body }}
        run: ./gradlew modrinth

      - name: Publish to Hangar
        env:
          RELEASE: true
          HANGAR_TOKEN: ${{ secrets.HANGAR_TOKEN }}
          VERSION_NAME: ${{ github.event.release.name }}
          VERSION: ${{ github.event.release.tag_name }}
          CHANGELOG: ${{ github.event.release.body }}
        run: ./gradlew publishPluginPublicationToHangar
  publish-description:
    name: Publish description
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Set up JDK
        uses: actions/setup-java@v5.7.0
        with:
          distribution: temurin
          java-version: 25
          cache: gradle

      - name: Update description (Modrinth)
        env:
          RELEASE: true
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          HANGAR_TOKEN: N/A
          VERSION_NAME: N/A
          VERSION: N/A
          CHANGELOG: N/A
        run: ./gradlew modrinthSyncBody --no-configuration-cache --no-build-cache

      - name: Update Description (Hangar)
        env:
          RELEASE: true
          MODRINTH_TOKEN: N/A
          HANGAR_TOKEN: ${{ secrets.HANGAR_TOKEN }}
          VERSION_NAME: N/A
          VERSION: N/A
          CHANGELOG: N/A
        run: ./gradlew syncPluginPublicationMainResourcePagePageToHangar --no-configuration-cache --no-build-cache